server:
  port: 9998

spring:
  application:
    name: reactive-product-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # 注册中心地址
        cluster-name: bole #集群名称
        metadata:
          version: v1.0
    loadbalancer:
      ribbon:
        enabled: false

  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux
    username: root
    password:

logging:
  level:
    org.springframework.cloud.client.loadbalancer: DEBUG

