server:
  port: 9996

spring:
  application:
    name: reactive-stock-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # 注册中心地址
        cluster-name: bole #集群名称
        metadata:
          version: v1.0

  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux
    username: bole
    password: bole2020

